export default {
  th: {
    title: 'สร้างบัญชี',
    firstName: '่ชื่อ',
    lastName: 'นามสกุล',
    email: 'อีเมล',
    password: 'รหัสผ่าน',
    confirmPassword: 'ยืนยันรหัสผ่าน',
    agree1: 'ฉันยอมรับ ',
    agree2: ' และได้ทำการอ่าน ',
    tou: 'ข้อบังคับการใช้งาน',
    privacy:'ข้อตกลงความเป็นส่วนตัว',
    newsletter: 'ต้องการรับข่าวสารจากเรา',
    registerBtn: 'สร้างบัญชี',
    gotAccount: 'มีบัญชีแล้ว?',
    login: 'ล็อคอินเลย!',
  },
  en: {
    title: 'Register',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    agree1: 'I agree to the ',
    agree2: ' and have read and understand the ',
    tou: 'Terms of Use',
    privacy:'Privacy Policy',
    newsletter: 'Sign me up for the newsletter',
    registerBtn: 'Register',
    gotAccount: 'Have an account?',
    login: 'Login now!',
  },
};
