export default {
  th: {
    saveProject: 'บันทึกโปรเจค',
    publish: 'เผยแผร่โปรเจค',
    cancel: 'ยกเลิก',
    next: 'ถัดไป',
    prev: 'ก่อนหน้า',
    basic: {
      title: 'Basics',
      header: 'ข้อมูลพื้นฐาน',
      description: 'แนะนำโปรเจคและสร้างความน่าสนใจให้กับโปรเจคของคุณ. ข้อมูลเหล่านี้จะเปรียบเสมือนหน้าตาของโปรเจคคุณ',
      projectTitle: 'ชื่อโปรเจค',
      projectTitleDescription: 'ตั้งชื่อให้กับโปรเจคของคุณ',
      projectTagline: 'คำเปรยของโปรเจค',
      projectTaglineDescription: 'ข้อความสั้นๆที่อธิบายโปรเจคของคุณ',
      projectImage: 'รูปภาพโปรเจค',
      projectImageDescription: 'อัพโหลดรูปภาพของโปรเจคของคุณ',
      projectImagePlaceholder: 'กด หรือ ลาก รูปภาพมาที่นี่เพื่ออัพโหลด',
      projectTags: 'แท็ค',
      projectTagsDescription: 'ใส่คำที่บ่งบอกถึงโปรเจคของคุณ สูงสุด 5 คำ',
    },
    story: {
      title: 'Story',
      header: 'ความเป็นมาของโปรเจค',
      description: 'บอกเล่าเรื่องราวของโปรเจค,อธิบายว่าทำไมคนถึงควรต้องสนใจโปรเจคนี้อย่างตรงประเด็นและไม่ยาวจนเกินไป.',
      projectDesc: 'คำอธิบายโปรเจค',
      projectDescDescription: 'บอกเล่าความเป็นมา เหตุผล เรื่องราว และผลที่คาดว่าจะได้รับ รวมถึงเรื่องราวของตัวคุณเอง',
    },
    faq: {
      title: 'FAQ',
      header: 'คำถามที่พบบ่อย',
      description: 'เพิ่มคำถามที่พบบ่อยของโปรเจคคุณ เพื่อตอบคำถามที่อาจจะพบได้บ่อยแก่คนที่สนใจโปรเจคคุณ',
      addField: 'เพิ่ม',
    },
    contributor: {
      title: 'Contributor',
      header: 'เพิ่มผู้ร่วมโปรเจค',
      description: 'เพิ่มผู้ที่ร่วมงานกับโปรเจคนี้',
    },
    people: {
      title: 'People',
      header: 'เพิ่มตำแหน่งงาน',
      description: 'ระบุตำแหน่งหรือรูปแบบการทำงานของบุคคลที่ต้องการมาร่วมโปรเจคนี้',
      addField: 'เพิ่ม',
    },
  },
  en: {
    saveProject: 'Save your project',
    publish: 'Publish',
    cancel: 'Cancel',
    next: 'Next',
    prev: 'Prev',
    basic: {
      title: 'Basics',
      header: 'Basic information',
      description: 'Make a good first impression: introduce your project objectives and entice people to learn more. This basic information will represent your project on your project page, on your project card, and in searches.',
      projectTitle: 'Project Title',
      projectTitleDescription: 'what is the title of your project?',
      projectTagline: 'Project Tagline',
      projectTaglineDescription: 'Provide a short description that best describes your project to your audience.',
      projectImage: 'Project Image',
      projectImageDescription: 'Upload a square image that represents your project.',
      projectImagePlaceholder: 'Click or drag file to this area to upload',
      projectTags: 'Tags',
      projectTagsDescription: 'Enter up to five keywords that best describe your project.',
    },
    story: {
      title: 'Story',
      header: 'Project Story',
      description: 'Tell people why they should be excited about your project. Get specific but be clear and be brief.',
      projectDesc: 'Project Description',
      projectDescDescription: 'Describe what you planning to do, why are you doing it, how you plan to make it happen, and who you are.',
    },
    faq: {
      title: 'FAQ',
      header: 'Frequently Ask Question',
      description: 'The FAQ section should provide the most common details that peoples are looking for when evaluating your project.',
      addField: 'Add Field',
    },
    contributor: {
      title: 'Contributor',
      header: 'Add Contributor',
      description: 'Add people who are working for this project or contribute something to the project.',
    },
    people: {
      title: 'People',
      header: 'Add Jobs',
      description: 'Add description for people you want to work with.',
      addField: 'Add Field',
    },
  },
};
