export default {
  th: {
    title: 'ค้นหาโปรเจค',
    or: 'หรือ',
    in: 'ใน',
    selectCatagory: 'เลือกหมวดหมู่',
    selectRole: 'เลือกหน้าที่',
    selectState: 'เลือกพื้นที่',
    searchText: 'ใส่ข้อควมค้นหา',
    projects: 'โปรเจค',
    categories: 'หมวดหมู่',
    student: 'นักเรียน / นักศึกษา',
    startUp: 'SME / Startup',
    industrial: 'บริษัท / โรงงาน',
    sortBy: 'จัดเรียงโดย',
    dateAdded: 'วันที่สร้าง',
    trending: 'ความนิยม',
    lastUpdate: 'ปรับปรุงล่าสุด',
    textPopupSearch: 'โปรดค้นหาโดยใช้คำเต็ม',
    showMore: 'แสดงเพิ่ม!',
    noMore: 'หมดแล้วจ้า!',
    empty: 'Much space, Such empty, WOW!',
    roleNeeded: 'ตำแหน่งที่ค้องการ',
    featured: 'แนะนำ',
    sponsored: 'ผู้สนับสนุนุ',
    by: 'โดย',
  },
  en: {
    title: 'Explore',
    or: 'Or',
    in: 'in',
    selectCatagory: 'Select Category',
    selectRole: 'Select Role',
    selectState: 'Select State',
    searchText: 'input search text',
    projects: 'Projects',
    categories: 'CATEGORIES',
    student: 'Student',
    startUp: 'SME / Startup',
    industrial: 'Company / Industrial',
    sortBy: 'Sort by',
    dateAdded: 'Date Added',
    trending: 'Trending',
    lastUpdate: 'Lastest Update',
    textPopupSearch: 'Only support fulltext search',
    showMore: 'Show more!',
    noMore: 'No more!',
    empty: 'Much space, Such empty, WOW!',
    roleNeeded: 'Role needed',
    featured: 'Featured',
    sponsored: 'Sponsored',
    by: 'by',
  },
};
